### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by eilifmRS** [phobson/bridgescour#1]
I'm interested in using this as the starter for a ASOS parser.  What is your license?

**Comment by phobson** [comment]
Oh man. you definitely don't want to use this repo.

you want to use:
https://github.com/tomp/python-metar

and this:
https://github.com/Geosyntec/cloudside

```
import cloudside
data = cloudside.getASOSData('KPDX', '2009-09-01', '2016-10-01')
```

**Comment by eilifmRS** [comment]
Those are good finds, thank you!

**Comment by phobson** [comment]
no problem! I wrote `cloudside`, which is descendant of the abomination that is this repo.
